//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsForm_OE_102_AnaProje.OgrenciIsleri.OgrEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDepartments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblDepartments()
        {
            this.TblOgrBilgiler = new HashSet<TblOgrBilgiler>();
        }
    
        public int Id { get; set; }
        public string BolumAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOgrBilgiler> TblOgrBilgiler { get; set; }
    }
}
