//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsForm_OE_102_AnaProje.OgrenciIsleri.OgrEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOgrBilgiler
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string TcNo { get; set; }
        public string OgNo { get; set; }
        public Nullable<int> BolumId { get; set; }
        public Nullable<int> SehirId { get; set; }
    
        public virtual TblSehirler TblSehirler { get; set; }
        public virtual TblDepartments TblDepartments { get; set; }
    }
}
