CREATE TABLE [dbo].[TblSehirler](
    [id] [int] IDENTITY(1,1) NOT NULL,
    [sehir] [nvarchar](255) NULL,
 CONSTRAINT [PK_TblSehirler] PRIMARY KEY CLUSTERED 
(
    [id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[TblSehirler] ON
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (1, N'ADANA')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (2, N'ADIYAMAN')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (3, N'AFYON')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (4, N'AĞRI')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (5, N'AMASYA')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (6, N'ANKARA')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (7, N'ANTALYA')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (8, N'ARTVİN')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (9, N'AYDIN')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (10, N'BALIKESİR')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (11, N'BİLECİK')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (12, N'BİNGÖL')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (13, N'BİTLİS')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (14, N'BOLU')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (15, N'BURDUR')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (16, N'BURSA')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (17, N'ÇANAKKALE')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (18, N'ÇANKIRI')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (19, N'ÇORUM')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (20, N'DENİZLİ')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (21, N'DİYARBAKIR')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (22, N'EDİRNE')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (23, N'ELAZIĞ')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (24, N'ERZİNCAN')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (25, N'ERZURUM')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (26, N'ESKİŞEHİR')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (27, N'GAZİANTEP')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (28, N'GİRESUN')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (29, N'GÜMÜŞHANE')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (30, N'HAKKARİ')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (31, N'HATAY')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (32, N'ISPARTA')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (33, N'İÇEL')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (34, N'İSTANBUL')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (35, N'İZMİR')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (36, N'KARS')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (37, N'KASTAMONU')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (38, N'KAYSERİ')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (39, N'KIRKLARELİ')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (40, N'KIRŞEHİR')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (41, N'KOCAELİ')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (42, N'KONYA')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (43, N'KÜTAHYA')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (44, N'MALATYA')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (45, N'MANİSA')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (46, N'KAHRAMANMARAŞ')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (47, N'MARDİN')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (48, N'MUĞLA')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (49, N'MUŞ')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (50, N'NEVŞEHİR')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (51, N'NİĞDE')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (52, N'ORDU')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (53, N'RİZE')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (54, N'SAKARYA')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (55, N'SAMSUN')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (56, N'SİİRT')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (57, N'SİNOP')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (58, N'SİVAS')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (59, N'TEKİRDAĞ')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (60, N'TOKAT')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (61, N'TRABZON')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (62, N'TUNCELİ')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (63, N'ŞANLIURFA')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (64, N'UŞAK')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (65, N'VAN')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (66, N'YOZGAT')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (67, N'ZONGULDAK')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (68, N'AKSARAY')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (69, N'BAYBURT')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (70, N'KARAMAN')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (71, N'KIRIKKALE')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (72, N'BATMAN')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (73, N'ŞIRNAK')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (74, N'BARTIN')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (75, N'ARDAHAN')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (76, N'IĞDIR')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (77, N'YALOVA')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (78, N'KARABÜK')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (79, N'KİLİS')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (80, N'OSMANİYE')
INSERT [dbo].[TblSehirler] ([id], [sehir]) VALUES (81, N'DÜZCE')
SET IDENTITY_INSERT [dbo].[TblSehirler] OFF